services:
  remo-auth:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8444:8444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8444/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
